### ISSUE TITLE
"host is in another meeting" zoom issue

### ISSUE THREAD

**Issue by LisaZ94** [animalzinc/animalzinc.github.io#3]
For my "Intro Call - Tracey Lloyd - Analyst" call a Zoom window popped up and said the host was is another meeting. I ended up just emailing her with a new link that we used. 

![image](https://cloud.githubusercontent.com/assets/27298626/24925979/0f8b9fc8-1ec8-11e7-9d86-851c469b7a56.png)

**Comment by smalter** [comment]
hey @LisaZ94, please log this in panther's issues. https://github.com/animalzinc/panther/issues
